# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия')),
                ('leaving_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Время ухода')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Отметки',
                'verbose_name': 'Отметка',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('acronym', models.CharField(max_length=20, verbose_name='Сокращенно')),
            ],
            options={
                'verbose_name_plural': 'Отделы',
                'verbose_name': 'Отдел',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код сотрудника')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
                'verbose_name': 'Сотрудник',
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee'),
        ),
    ]
